### ISSUE TITLE
Basic security architecture

### ISSUE THREAD

**Issue by christianbauer** [openremote/m1designer#8]
_Need to build security architecture from scratch, there are currently no constraints._
# User install workflow
1. Unpack the box
2. Start controller application, open start page in browser (can be automatic with native integration?)
3. User is prompted to register with name and password (the name can be a person or client identifier)
   1. Option: User picks "Use bookmarklet" and drags generated bookmarklet (see http://benlog.com/2007/02/06/beamauth-two-factor-web-authentication-with-a-bookmark/) into the browser bar, clicking on it will send an HTTP basic authentication request and then redirect to the initial page
   2. Option: User picks "Use regular login" and the browser will present the user with a regular authentication dialog, its the user's job to make a bookmark and possibly store the credentials in the browser/OS keychain
# Registration

After the first user registered, registration must no longer be possible, open registration can be re-enabled in application security configuration. The first user is the initial superuser, with all permissions.
# Authentication & Authorization
1. Build a local user/password hash database and a minimal role/permission system
2. Integrate cloud services (which? our Beehive Keycloa)
3. The professional version of OR3 could be bundled with preconfigured Keycloak service.
# Transport
- TLS + HTTP Basic Authentication
- HTTP XSRF protection either through CORS or if that's still a problem, through double-submit of form hash in header (cookie) and body (json field)
- WebSocket XSRF protection (see https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html) must be enabled on WebsocketComponent with Jetty CrossOriginFilter
- https://en.wikipedia.org/wiki/JSON_Web_Token
- Consider "Unlimited Strength Jurisdiction Policy" package for the JVM and if/how we need those algorithms
- Java Problems: http://web-in-security.blogspot.ca/2015/09/practical-invalid-curve-attacks.html

**Comment by richturner** [comment]
# Context Broker Accessibility

- The manager web server needs to be accessible from the Context Broker (for context provider callbacks)
- The CB runs in its' own docker container with its' own network interface so the manager web server needs to be visible from this interface
